### ISSUE TITLE
grpc-web to grpc support

### ISSUE THREAD

**Issue by sam-celer** [haproxy/haproxy#1524]
### Your Feature Request

It would be useful to implement something similar to the grpc_web filter in Envoy to translate grpc-web to grpc.
Currently we have to have haproxy -> envoy -> webserver. It would be nice to be able to get rid of envoy

For reference: https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/grpc_web/grpc_web_filter.cc 7

### What are you trying to do?

Convert grpc-web to grpc

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.4-de45672 2020/09/30 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.4.html
Running on: Linux 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-39)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

**Comment by wtarreau** [comment]
Hello,

we would really appreciate it if instead of saying "do like this product" you could elaborate a bit more on what you expect, what are your use cases etc. I'm personally not familiar with the difference between grpc and grpc-web, and it's not by reading another piece of code that it gives me any background. Also, use cases are extremely important to make sure we try to address a class of problems instead of a single one. It may allow others to chime in and explain their slightly different ones for example, that we'll need to figure how to best serve everyone.

Thanks!

**Comment by git001** [comment]
Well I think @sam-celer refer to https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md 

The documentation in Envoy isn't very detailed about this filter.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/filter/http/grpc_web/empty/grpc_web
> cite: This extension is intended to be robust against untrusted downstream traffic. It assumes that the upstream is trusted.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/intro/terminology
> Downstream: A downstream host connects to Envoy, sends requests, and receives responses.
> Upstream: An upstream host receives connections and requests from Envoy and returns responses.

But I agree with @wtarreau it would be much more clear when you write what you want to solve.
I would also help when you share the envoy config to see how you configured the filter :-)

**Comment by sam-celer** [comment]
Thanks for your time on this topic.

My understanding of what envoy does is very limited. I just managed the architecture and it bothers me to have two proxies. Ideally I only want to use haproxy.
From what I can gather from the application team, there is a react front-end sending grpc-web but the backend web server only understands grpc. So we put envoy in the middle to do the translation between the two protocols.

Envoy config below

```
static_resources:
  listeners:
  - address:
      socket_address:
        address:  127.0.0.1
        port_value: 25080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                 prefix: ""
                 headers:
                 - name: "X-Grpc-Web"
                route:
                  cluster: grpc_service_futures
                  max_grpc_timeout: 0s
                  timeout: 0s
              - match:
                  prefix: ""
                route:
                  cluster: http2_service_futures
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization-token
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router

  - address:
      socket_address:
        address:  127.0.0.1
        port_value: 25085
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                 prefix: ""
                 headers:
                 - name: "X-Grpc-Web"
                route:
                  cluster: grpc_service_lite
                  max_grpc_timeout: 0s
                  timeout: 0s
              - match:
                  prefix: ""
                route:
                  cluster: http2_service_lite
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization-token
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router

  - address:
      socket_address:
        address:  127.0.0.1
        port_value: 25090
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                 prefix: ""
                 headers:
                 - name: "X-Grpc-Web"
                route:
                  cluster: grpc_service_fx
                  max_grpc_timeout: 0s
                  timeout: 0s
              - match:
                  prefix: ""
                route:
                  cluster: http2_service_fx
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization-token
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router

  - address:
      socket_address:
        address:  127.0.0.1
        port_value: 25095
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                 prefix: ""
                 headers:
                 - name: "X-Grpc-Web"
                route:
                  cluster: grpc_service_basemetals
                  max_grpc_timeout: 0s
                  timeout: 0s
              - match:
                  prefix: ""
                route:
                  cluster: http2_service_basemetals
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization-token
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router

  clusters:
  - name: grpc_service_futures
    connect_timeout: 0.15s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 11000
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25081

  - name: http2_service_futures
    connect_timeout: 0.15s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25082

  - name: grpc_service_lite
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 11000
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25086

  - name: http2_service_lite
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25087

  - name: grpc_service_fx
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 11000
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25091

  - name: http2_service_fx
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25092

  - name: grpc_service_basemetals
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 11000
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25096

  - name: http2_service_basemetals
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 25097
```
