### ISSUE TITLE
fastcgi is not supported with official docker image ?

### ISSUE THREAD

**Issue by Krikooo** [haproxy/haproxy#2348]
### Detailed Description of the Problem

Following this article for my haproxy conf: https://www.haproxy.com/blog/load-balancing-php-fpm-with-haproxy-and-fastcgi

I guet the following error when I try to launch my docker image:
```
Attaching to local-haproxy-1
local-haproxy-1  | [NOTICE]   (1) : haproxy version is 2.8.3-86e043a
local-haproxy-1  | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
local-haproxy-1  | [ALERT]    (1) : config : [/usr/local/etc/haproxy/haproxy.cfg:21] : 'server phpservers/172.17.0.2:9000' : unknown keyword 'fcgi'.
local-haproxy-1  | [ALERT]    (1) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
local-haproxy-1  | [ALERT]    (1) : config : Fatal errors found in configuration.
local-haproxy-1 exited with code 1
```

Dockerfile:
```
FROM haproxy:2.8
COPY config/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
```

docker-compose.yaml
```
version: "3.9"  # optional since v1.27.0
services:
  haproxy:
    build:
      context: .
      dockerfile: ./docker/haproxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/usr/local/etc/haproxy/certs
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
networks:
  sc_network:
    external: true
```

### Expected Behavior

to get my haproxy server up.

### Steps to Reproduce the Behavior

1. Try to start haproxy with docker image with fcgi directive

### What is your configuration?

```haproxy
FROM haproxy:2.8
COPY config/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
```

docker-compose.yaml
```
version: "3.9"  # optional since v1.27.0
services:
  haproxy:
    build:
      context: .
      dockerfile: ./docker/haproxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/usr/local/etc/haproxy/certs
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
networks:
  sc_network:
    external: true
```
```


### Output of `haproxy -vv`

```plain
local-haproxy-1  | [NOTICE]   (1) : haproxy version is 2.8.3-86e043a
local-haproxy-1  | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
local-haproxy-1  | [ALERT]    (1) : config : [/usr/local/etc/haproxy/haproxy.cfg:21] : 'server phpservers/172.17.0.2:9000' : unknown keyword 'fcgi'.
local-haproxy-1  | [ALERT]    (1) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
local-haproxy-1  | [ALERT]    (1) : config : Fatal errors found in configuration.
local-haproxy-1 exited with code 1
```
