### ISSUE TITLE
503 when timeout in the queue ends with empty reply from server

### ISSUE THREAD

**Issue by vvucetic** [haproxy/haproxy#2404]
### Detailed Description of the Problem

When server queue is full, request ends with empty reply from HAProxy, logged as 503 and status `sQ`. That happens in `2.6.16-alpine` as well as all never versions.

### Expected Behavior

In the version `2.6.15-alpine` however, request is properly accepted in the queue regardless if the server queue is full and stays in the, I believe, backend queue until `timeout queue` and then responds with 503 error page (but not empty response)

Something changed between the versions and it's easy to reproduce.

### Steps to Reproduce the Behavior

1. Make backend with 1 server with maxconn 1.
2. Make sure that the server responds slowly so it gives you time to send another request
3. Make one request which will take the connection spot. Make another immediately after. 

In version `2.6.15-alpine` you'll get 503 after set timeout. In version `2.6.16-alpine` the second request will immediately end up with an empty response. I can share docker-compose with mock service if needed. 

### What is your configuration?

```haproxy
global
    daemon
    maxconn 10000
    log stdout format raw local0 debug
    tune.lua.session-timeout 40ms

defaults
    mode http
    log global
    option httplog
    timeout connect 5s
    timeout client 91s
    timeout server 91s
    maxconn 8000
    option forwardfor
    option abortonclose
    retry-on conn-failure 504
    compression algo gzip
    compression type text/html text/plain application/json

frontend http
    mode http
    bind :8080
    tcp-request inspect-delay 5s

    http-request set-var(txn.rl_backend_company) str(unknown)
    http-after-response set-header x-haproxy-rl-backend-company %[var(txn.rl_backend_company)]

    use_backend default

backend default
    maxconn 10000
    timeout queue 10ms
    mode http

    default-server init-addr last,libc,none check inter 1s resolvers docker maxconn 1
    server s1 service:6000

resolvers docker
    nameserver docker 127.0.0.11:53
    accepted_payload_size 8192 # allow larger DNS payloads
```

### Output of `haproxy -vv`

```plain
(shared exact versions)
```

**Comment by vvucetic** [comment]
If you want to easily reproduce, here are additional mock files to set up environment

## Mock service
`service_mock/dockerfile`
```
FROM python:3.7-alpine

RUN mkdir /app

WORKDIR /app

ADD requirements.txt /app

ADD main.py /app

RUN pip3 install -r requirements.txt

CMD ["gunicorn", "-w 4", "-b", "0.0.0.0:6000", "main:app", "--error-logfile gunicorn.error.log", "--access-logfile gunicorn.log", "--capture-output"]

```

`service_mock/main.py`
```
import time

import flask

app = flask.Flask(__name__)


@app.route('/mock/')
def hello_world():
    resp = flask.Response("Service result.")
    return resp


@app.route('/mock/slow')
def slow_response():
    time.sleep(10)
    resp = flask.Response("Slow service result.")
    return resp
```
`service_mock/requirements.txt`
```
Flask>=2.2.2
gunicorn>=19,<20
```
`docker-compose.yml`
```
version: '3.7'
services:
  haproxy:
    image: haproxy:2.6.15-alpine # >=2.6.16-alpine doesnt work
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
       - ./haproxy_mock/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  service:
    build:
      context: ./service_mock
      dockerfile: Dockerfile
    expose:
      - 6000
    volumes:
      - ./service_mock/:/app
```

I already shared mock haproxy config. If you just change the docker tag of the haproxy, you can observe different behavior on the second request that you can make like this

`curl -v localhost:8080/mock/slow`

![image](https://github.com/haproxy/haproxy/assets/1523657/81ff295e-754b-41b4-a8c5-479187b333ec)
![image](https://github.com/haproxy/haproxy/assets/1523657/7824625b-81b0-4b70-9c7a-0e26a55eea49)
