### ISSUE TITLE
Flexibility with PROXY protocol header on the same port?

### ISSUE THREAD

**Issue by polarathene** [haproxy/haproxy#2450]
Some implementations like [`go-proxyproto`](https://github.com/pires/go-proxyproto) have implemented a [policy system](https://github.com/pires/go-proxyproto/blob/v0.7.0/policy.go#L18) for making it possible to accept connections without PROXY protocol, while only accepting the header from trusted hosts. This is what Traefik uses and Caddy is changing to in their 2.8 release.

While documenting PROXY protocol support on a project, one of the reviewers referenced the PROXY protocol specification with the `MUST` wording that forbids this approach:

https://github.com/haproxy/haproxy/blob/2ed53ae4a02ba49f529addb9003b747c8ab281b1/doc/proxy-protocol.txt#L176-L182

> _MUST not try to guess whether the protocol header is present or not. This means that the protocol explicitly prevents port sharing between public and private access._

While the `SHOULD` encourages minimizing risk by restricting what hosts are trusted.

It would seem that if you manage what hosts are trustworthy, that's what matters here when accepting PROXY headers, but those same hosts could just as well not provide the PROXY header and not have PROXY protocol apply?

Isn't the only concern really that the receiver must not use the PROXY header when the connection is from an untrusted host? Perhaps the specification should be revised to be more flexible on that point?

---

**References:**
- `go-proxyproto` landed a policy feature roughly a year ago related to internal vs external traffic [to the same port motivated by kubernetes deployments](https://github.com/pires/go-proxyproto/issues/95).
- On the project I contributed docs to, this issue raised a debate about a need for duplicating ports of a service just for separate PROXY protocol handling for similar reasons. While Dovecot can configure trusted hosts, Postfix seems to lack the equivalent feature (_when PROXY protocol is enabled for a service port, the remote IP is already the client IP as would be expected_).

**Comment by TimWolla** [comment]
> It would seem that if you manage what hosts are trustworthy, that's what matters here when accepting PROXY headers, but those same hosts could just as well not provide the PROXY header and not have PROXY protocol apply?

That would be insecure, because if a client knows that the host won't add the PROXY header for a given connection, but also knows that the host is generally considered to be trustworthy, then that client could just send the PROXY header itself at the beginning of the connection.

**Comment by polarathene** [comment]
> then that client could just send the PROXY header itself at the beginning of the connection.

Sorry I don't follow?

With a reverse proxy like Caddy or Traefik which does allows this flexibility, how is this insecure?

<details>
<summary>Original response</summary>

Just so I don't misunderstand you, this is further clarification for me:
- Client (A)
- Reverse Proxy (B) Traefik
- Service (C) Caddy

Connection flow: `A => B => C`

- The client is untrusted, any attempt to send PROXY protocol header from them is discarded.
- Reverse Proxy connects to service with PROXY protocol, and the service trusts the the reverse proxy.

Meanwhile:
- A separate route through Traefik for a client request could connect to Caddy on the same port, but without providing PROXY protocol.
- Caddy (since 2.8) having trusted traffic from Traefik will still accept the connection.
- Traefik like Caddy must configure any trusted clients to accept PROXY protocol connections from, which Traefik would then forward to Caddy (_use of PROXY protocol is only for TCP services which require TCP routers in Traefik, it is per-service however_)
- While Traefik cannot use PROXY protocol for HTTP services (which require HTTP routers), Caddy presently only manages HTTP traffic (Layer 7), not TCP (Layer 4), although there is a separate Caddy app (L4) that can provide TCP support (_although slightly separate integration AFAIK_). For Caddy this is handled in the `servers` config which is related to Layer 4.

**Where is the security issue?**

If you already trust a host to receive PROXY headers from, then what is the consequence of accepting traffic that is not presenting that header?

I think given that the receiving end disregards any PROXY header unless trusted, makes your concern invalid?

Perhaps there are other factors related to a deployment that cause the conflicting opinion on security here? 🤷‍♂️ 

</details>

---

I've provided an example below that's quite easy to run with `docker compose` installed, you only need to copy/paste the file and run two commands.

Please point out how this is insecure:
- How a client can send a PROXY header to exploit the Caddy service configured below.
- When Caddy only trusts Traefik with the PROXY protocol, but makes the PROXY protocol optional for connections to that port.

**Comment by polarathene** [comment]
Here is a reproduction environment with both Traefik and Caddy involved. See the curl commands at the end for various scenarios tested.

```yaml
# compose.yaml
# Usage:
# - Bring up services: docker compose up -d --force-recreate
# - Run curl tests: docker compose run --rm client

services:
  reverse-proxy:
    image: docker.io/traefik:3.0
    hostname: traefik.internal.test
    networks:
      default:
        ipv4_address: 172.16.42.10
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=dms-test-network
      # Traefik will redirect any incoming HTTP requests to HTTPS:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # Equivalent to Caddy `servers.trusted_proxies` for accepting `X-Forwaded-*` headers:
      # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
      # NOTE: This is technically always enabled for Layer 4 (TCP) router/services.
      # NOTE: Both entrypoints would need to be enabled if requests starts with HTTP/80,
      #       as either entrypoint would strip those headers otherwise.
      #- --entryPoints.web.forwardedHeaders.insecure=true
      #- --entryPoints.websecure.forwardedHeaders.insecure=true
      - --entryPoints.websecure.address=:443
    # CAUTION: Production usage should configure socket access better (see Traefik docs)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"

  web:
    # Can use this instead of build once Caddy 2.8 is released:
    #image: caddy:2.8
    hostname: caddy.internal.test
    networks:
      default:
        ipv4_address: 172.16.42.20
    # Caddy 2.8 makes PROXY protocol header optional on
    # the receiving port, just like Traefik.
    # Build master branch for unreleased Caddy 2.8:
    build:
     dockerfile_inline: |
       FROM caddy:2.7-builder AS builder
       RUN xcaddy build master

       FROM caddy:2.7
       COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    labels:
      - traefik.enable=true

      # Only TCP services can enable PROXY Protocol:
      # TLS passthrough delegates TLS termination to Caddy instead:
      - traefik.tcp.routers.websecure.rule=HostSNI(`*`)
      - traefik.tcp.routers.websecure.tls.passthrough=true
      - traefik.tcp.routers.websecure.entrypoints=websecure
      - traefik.tcp.routers.websecure.service=with-proxy
      # Route to port 443 with PROXY protocol, Caddy will handle TLS:
      - traefik.tcp.services.with-proxy.loadbalancer.server.port=443
      - traefik.tcp.services.with-proxy.loadbalancer.proxyProtocol.version=2

      # Skips PROXY protocol connection for https://no-proxy-header.test
      - traefik.tcp.routers.no-proxy-header.rule=HostSNI(`no-proxy-header.test`)
      - traefik.tcp.routers.no-proxy-header.tls.passthrough=true
      - traefik.tcp.routers.no-proxy-header.entrypoints=websecure
      - traefik.tcp.routers.no-proxy-header.service=without-proxy
      # Route to port 443, Caddy will handle TLS:
      - traefik.tcp.services.without-proxy.loadbalancer.server.port=443

      # Skips PROXY protocol connection for https://https-router.test
      # Traefik will terminate TLS instead of delegating to Caddy (no passthrough).
      # Thus the Traefik cert is presented instead, and decrypted traffic is sent to Caddy.
      - traefik.http.routers.no-proxy-header.rule=Host(`traefik-https-router.test`)
      - traefik.http.routers.no-proxy-header.tls=true
      - traefik.http.routers.no-proxy-header.entrypoints=websecure
      - traefik.http.routers.no-proxy-header.service=without-proxy
      # Route to port 80, Traefik handled TLS:
      # NOTE: Caddy won't issue an HTTPS redirect for this host like it would others.
      - traefik.http.services.without-proxy.loadbalancer.server.port=80

    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

  # Only intended for running via `docker compose run --rm -it client`
  client:
    hostname: client.internal.test
    # An easy to recognize IP in the logs:
    networks:
      default:
        ipv4_address: 172.16.42.42
    # Prevent starting this service by default with `docker compose up`:
    profiles:
      - testing
    build:
      dockerfile_inline: |
        FROM alpine
        RUN apk add curl
    command: ash /tmp/run.sh
    configs:
      - source: curl-cmds
        target: /tmp/run.sh

networks:
  default:
    name: dms-test-network
    ipam:
      config:
        - subnet: "172.16.42.0/24"

configs:
  caddyfile:
    content: |
      # Global options:
      {
        local_certs

        # Enable ProxyProtocol for incoming Traefik connections:
        # https://caddyserver.com/docs/caddyfile/options#listener-wrappers
        servers {
          #log_credentials
          # Optionally trust HTTP headers from Traefik (regardless of TCP/HTTP router):
          trusted_proxies static 172.16.42.10/32

          listener_wrappers {
            # Must come before `tls`.
            proxy_protocol {
              # Only trust PROXY protocol connections from Traefik:
              allow 172.16.42.10/32
            }

            tls
          }
        }
      }

      # These docs are mostly applicable to HTTP routed traffic:
      # NOTE: TCP routers by Traefik do not understand HTTP traffic is handled,
      #       Thus any headers included (eg: X-Forwarded-For) are not discarded.
      # https://caddyserver.com/docs/caddyfile/options#client-ip-headers
      # > Pairing with trusted_proxies, allows configuring which headers to use to determine the client's IP address.
      # > By default, only X-Forwarded-For is considered.
      # https://caddyserver.com/docs/caddyfile/matchers#client-ip
      # > Only requests from trusted proxies will have their client IP parsed at the start of the request;
      # > untrusted requests will use the remote IP address of the immediate peer.
      # https://caddyserver.com/docs/caddyfile/matchers#remote-ip
      # > the first IP in the X-Forwarded-For request header, if present, will be preferred as the reference IP,
      # > rather than the immediate peer's IP, which is the default.

      (respond_with_details) {
        log

        # Requested Host     => The HTTP `Host` header
        # Remote Host IP     => The host connecting directly to Caddy (eg: Traefik)
        # Client IP          => The real client IP (requires PROXY protocol or direct connection)
        # ---
        # NOTE: Traefik only provides these headers for connections using HTTP router/services not TCP:
        # X-Forwarded-Host   => Requested host that Caddy will match to a site block
        # X-Forwarded-Server => Remote Host
        # X-Forwarded-For    => Client IP (Caddy will use this if `servers.trusted_proxies` is configured)
        # X-Real-Ip          => Client IP (Extra header from Traefik)

        respond <<EOF
          Caddy Received:
            Requested Host: {host}
            Remote Host IP: {remote_host}
            Client IP:      {client_ip}
            ---
            X-Forwarded-Host:   {header.X-Forwarded-Host}
            X-Forwarded-Server: {header.X-Forwarded-Server}
            X-Forwarded-For:    {header.X-Forwarded-For}
            X-Real-Ip:          {header.X-Real-Ip}
        EOF
      }

      example.test {
        import respond_with_details
      }

      no-proxy-header.test {
        import respond_with_details
      }

      http://traefik-https-router.test {
        import respond_with_details
      }

  curl-cmds:
    content: |
      #!/bin/sh

      # Curl options:
      # - `--insecure` (`-k`) to ignore local generated certs (Caddy/Traefik) fail to verify (CA not in trust store)
      # - `--location` (`-L`) to follow redirect for HTTP => HTTPS (used for direct Caddy example.test)
      # - `--header` (`-H`) add/modify request headers sent.
      # - `-w '\n'` for ensuring a final LF which is not part of the Caddy respond directive
      # - `--connect-to` routes traffic to the Traefik reverse proxy:
      #   https://curl.se/docs/manpage.html#--connect-to

      # TCP TLS router/service, with proxy header:
      # Both remote and client IP are for the Client (remote probably should remain as Traefik IP?):
      echo -e '\n- Client => Traefik (PROXY protocol) => Caddy (http://example.test)'
      curl -L -H "X-Forwarded-For: 1.2.3.4" --insecure --connect-to ::traefik.internal.test http://example.test -w '\n'

      # TCP TLS router/service, without proxy header:
      # Both remote and client IP are for Traefik (expected):
      # WARNING: With Caddy `servers.trusted_proxies` the curl client can add headers to fool Caddy here,
      #   as routing Layer 4 traffic in Traefik is not concerned with Layer 7 (HTTP).
      #   However when the PROXY protocol is used (like prior curl request), it has precedence for setting Client IP.
      echo -e '\n- Client => Traefik (no PROXY protocol) => Caddy (http://no-proxy-header.test)'
      curl -L -H 'X-Forwarded-For: 1.2.3.4' --insecure --connect-to ::traefik.internal.test http://no-proxy-header.test -w '\n'

      # HTTP TLS router/service:
      # Caddy `servers.trusted_proxies` must be enabled to resolve Client IP correctly here (expected), otherwise it will represent the Traefik IP.
      # As the request is via an HTTP router the curl header is ignored - unless allowing the Traefik entrypoint to forward these headers from clients.
      echo -e '\n- Client => Traefik (no PROXY protocol) => Caddy (http://traefik-https-router.test)'
      curl -L -H 'X-Forwarded-For: 1.2.3.4' --insecure --connect-to ::traefik.internal.test http://traefik-https-router.test -w '\n'

      echo -e '\n------\n'

      # All three of these curl requests respond with remote and client IP as that of the client (which is correct):
      echo -e '\n- Client => Caddy (http://example.test)'
      curl -L --insecure --connect-to ::caddy.internal.test http://example.test -w '\n'

      echo -e '\n- Client => Caddy (http://no-proxy-header.test)'
      curl -L --insecure --connect-to ::caddy.internal.test http://no-proxy-header.test -w '\n'

      # Internally to Caddy this endpoint doesn't offer HTTPS:
      echo -e '\n- Client => Caddy (http://traefik-https-router.test)'
      curl --connect-to ::caddy.internal.test http://traefik-https-router.test -w '\n'
```

Output from running the two commands at the start of that config file:

```
- Client => Traefik (PROXY protocol) => Caddy (http://example.test)
  Caddy Received:
    Requested Host: example.test
    Remote Host IP: 172.16.42.42
    Client IP:      172.16.42.42
    ---
    X-Forwarded-Host:
    X-Forwarded-Server:
    X-Forwarded-For:    1.2.3.4
    X-Real-Ip:

- Client => Traefik (no PROXY protocol) => Caddy (http://no-proxy-header.test)
  Caddy Received:
    Requested Host: no-proxy-header.test
    Remote Host IP: 172.16.42.10
    Client IP:      1.2.3.4
    ---
    X-Forwarded-Host:
    X-Forwarded-Server:
    X-Forwarded-For:    1.2.3.4
    X-Real-Ip:

- Client => Traefik (no PROXY protocol) => Caddy (http://traefik-https-router.test)
  Caddy Received:
    Requested Host: traefik-https-router.test
    Remote Host IP: 172.16.42.10
    Client IP:      172.16.42.42
    ---
    X-Forwarded-Host:   traefik-https-router.test
    X-Forwarded-Server: traefik.internal.test
    X-Forwarded-For:    172.16.42.42
    X-Real-Ip:          172.16.42.42

------


- Client => Caddy (http://example.test)
  Caddy Received:
    Requested Host: example.test
    Remote Host IP: 172.16.42.42
    Client IP:      172.16.42.42
    ---
    X-Forwarded-Host:
    X-Forwarded-Server:
    X-Forwarded-For:
    X-Real-Ip:

- Client => Caddy (http://no-proxy-header.test)
  Caddy Received:
    Requested Host: no-proxy-header.test
    Remote Host IP: 172.16.42.42
    Client IP:      172.16.42.42
    ---
    X-Forwarded-Host:
    X-Forwarded-Server:
    X-Forwarded-For:
    X-Real-Ip:

- Client => Caddy (http://traefik-https-router.test)
  Caddy Received:
    Requested Host: traefik-https-router.test
    Remote Host IP: 172.16.42.42
    Client IP:      172.16.42.42
    ---
    X-Forwarded-Host:
    X-Forwarded-Server:
    X-Forwarded-For:
    X-Real-Ip:
```

I think you are referring to `Client => Traefik (no PROXY protocol) => Caddy (http://no-proxy-header.test)`?
- The client IP would otherwise be `172.16.42.10` (Traefik) which isn't anymore helpful at knowing the actual client.
- The main caveat here is configuration with Traefik using a TCP router doesn't sanitize the HTTP headers. So without PROXY protocol it's vulnerable to forgery from the client.
- But this is only relevant when you care about a correct client IP which may not matter for this route, while it may for others. If using a TCP router/service in Traefik, getting a trustworthy client IP requires PROXY protocol.

Caddy could just as easily not trust those headers via `servers.trusted_proxies` (_unrelated to PROXY protocol trust_). Although that would likewise break the no PROXY protocol HTTP router in Traefik that was working correctly and not subject to request header forgery in `Client => Traefik (no PROXY protocol) => Caddy (http://traefik-https-router.test)` (_would then report Traefik IP as client IP_).

---

So the question is:
- Why does the specification have `MUST` on the receiver not being flexible with PROXY protocol header handling?
- Why is the expectation of only trusted hosts for PROXY protocol a `SHOULD`?
  - If it's an optional feature for the proper security to trust, then doesn't that permit conditionally handling which hosts can connect without PROXY protocol?
  - Likewise, why should that be limited to the host IP vs allowing PROXY protocol connections from trusted hosts, but not mandating the connection uses PROXY protocol?

Given that:
- For a reverse proxy like Caddy and Traefik above, either can be a receiver and have multiple services that they connect to.
- As mentioned previously, kubernetes manages traffic slightly differently that routing to ingress controller is inefficient vs a trusted internal service having a direct connection to another service where client IP is not proxied, thus no PROXY protocol is needed.

Do you really need to mandate separate ports? Isn't that achieving the same as a trust policy handled on the same port?
