### ISSUE TITLE
DNS resolver doesn't respect the `hold valid 1s` settings

### ISSUE THREAD

**Issue by twang2218** [haproxy/haproxy#74]
I'm using docker to reproduce the problem. I set up a 3 containers environment, here is the `docker-compose.yml`

```yaml
version: '2'
services:
    haproxy:
        image: haproxy:latest
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
            - "80:80"
        depends_on:
            - app
            - syslog
    app:
        build: ./app/.
    syslog:
        image: bobrik/syslog-ng:latest
        volumes:
            - ./log:/var/log/syslog-ng
```

`haproxy` is the frontend proxy service, and should load balanced to `app`, which might scaled to multiple containers, and output the log to `syslog`. `app` is just a simple node js server, which provide a http service at port 8000:

```javascript
const http = require('http');
const os = require('os');
const dns = require('dns');

const hostname = os.hostname();

dns.lookup(os.hostname(), (err, addr) => {
  const host_address = addr;

  const server = http.createServer((req, res) => {
    res.writeHeader(200, { 'Content-Type': 'text/plain' });
    const client = req.headers['x-forwarded-for'] ||
      req.connection.remoteAddress ||
      req.socket.remoteAddress ||
      req.connection.socket.remoteAddress;
    const log = `${client}\t → \t ${hostname} @ [${host_address}]`;
    res.end(log);
    console.log(log);
  });

  server.on('clientError', (err, socket) => {
    socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');
  });

  server.listen(8000, () => {
    console.log(`Listening on ${host_address}:8000 ...`);
  });
});
```

The haproxy settings is following:
```
global
    log syslog daemon

defaults
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

resolvers docker_dns
  nameserver dns "127.0.0.11:53"
  timeout retry   1s
  hold valid 1s

listen tcp_proxy
    mode tcp
    bind :80
    option tcplog
    log global
    server app app:8000 check resolvers docker_dns resolve-prefer ipv4
```

To run those services, just `docker-compose up -d`. 

At first, the haproxy resolved the `app` address correctly, even I restart the `app`, haproxy will notify the ip changes. 

However, after I scale the `app` by `docker-compose scale app=10`, the `haproxy` failed to resolve the other new `app` containers addresses, the `haproxy` will always keep the original resolved result. Unless that server is restarted, it will never try to resolve the `app` address again, even I use `hold valid 1s` settings.

I tried to enter the `haproxy` container and `nslookup app`, it correctly returned `app` address in random order. So it's not the docker embedded dns problem.

I'm using the latest haproxy docker image which provide haproxy 1.6.6:

```bash
# haproxy -v
HA-Proxy version 1.6.6 2016/06/26
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>
```

My docker version is `1.12-rc3`.

Is there anything that I did wrong? and is there a way to make HAProxy utilizing the multiple records returned from the Docker embedded DNS server for the load balancing? Thanks.
