### ISSUE TITLE
nolinger makes prom-exporter send a premature RST,ACK

### ISSUE THREAD

**Issue by pgaxatte** [haproxy/haproxy#896]
## Detailed description of the problem

When using the `option nolinger`, the embedded prometheus exporter sends a premature RST,ACK which breaks the client-side (either a simple curl or a prometheus scraper).

The normal stats backend does not seem to be affected.

## Expected behavior

The connection to the promex should be closed after haproxy has received all ACKs from the client.

## Steps to reproduce the behavior

1. Minimal configuration to reproduce the problem:
```
defaults
  option  nolinger

listen stats
  bind *:9000
  mode http
  http-request use-service prometheus-exporter if { path /metrics }
  stats enable
  stats refresh 10s
  stats uri /
```
2. Curl the promex endpoint and get a RST before obtaining all metrics:
```
$ curl http://localhost:9000/metrics
# HELP haproxy_process_nbthread Configured number of threads.
# TYPE haproxy_process_nbthread gauge
haproxy_process_nbthread 2
[...random number of lines...]
curl: (56) Recv failure: Connection reset by peer
```

Validated this problem on 2.1.8, 2.2.4 and 2.3-dev6.
I did not try on the latest master.

The test were done in Kubernetes, here is the YAML if you want to reproduce it:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-haproxy-etc
data:
  haproxy.cfg: |
    defaults
      option  nolinger

    listen stats
      bind *:9000
      mode http
      http-request use-service prometheus-exporter if { path /metrics }
      stats enable
      stats refresh 10s
      stats uri /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: test
    component: haproxy
  name: test-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      application: test
      component: haproxy
  template:
    metadata:
      labels:
        application: test
        component: haproxy
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - haproxy
        - -f
        - /usr/local/etc/haproxy/haproxy.cfg
        image: haproxy:2.3-dev6
        imagePullPolicy: IfNotPresent
        name: haproxy
        ports:
        - containerPort: 9000
          name: haproxy-stats
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          mountPropagation: None
          name: haproxy-etc
          readOnly: true
          subPath: haproxy.cfg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          name: test-haproxy-etc
          defaultMode: 292
          optional: false
        name: haproxy-etc
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3-dev6-b7ffe19 2020/10/10 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with gcc compiler version 8.3.0
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

```
Linux test-haproxy-75f47b859b-hvbf8 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 GNU/Linux
```
