### ISSUE TITLE
Haproxy controller GRPC  HTTP2 request does not work.

### ISSUE THREAD

**Issue by aliridha1510** [haproxy/haproxy#965]
I have a .net core grpc backend service that relies on the proxy information to tell it

if just test directly through node with curl, works fine.

```
➜  ~ grpcurl -plaintext 10.108.75.188:50051 build.stack.fortune.FortuneTeller/Predict
{
  "message": "Push where it gives and scratch where it itches."
}
```
if I query through HA answers:

```
grpcurl  -plaintext -H 'Host: foo.bar'   'XX.XX.XX.XX:30371'  build.stack.fortune.FortuneTeller/Predict 
Error invoking method "build.stack.fortune.FortuneTeller/Predict": failed to query for service descriptor "build.stack.fortune.FortuneTeller": rpc error: code = Unavailable desc = Bad Gateway: HTTP status code 502; transport: received the unexpected content-type "text/html"
```

note : I have the same environment with Rest API Spring  (http1.1 not Http2)and everything works

### kubectl get svc
```
haproxy-controller     haproxy-ingress             NodePort    10.98.53.182     <none>        80:30371/TCP,443:30462/TCP,1024:32346/TCP   4h4m    run=haproxy-ingress
haproxy-controller     ingress-default-backend     ClusterIP   10.108.75.188    <none>   50051/TCP   4h4m   run=ingress-default-backend
```

### deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-teller-app
  labels:
    k8s-app: fortune-teller-app
  namespace: haproxy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fortune-teller-app
  template:
    metadata:
      labels:
        k8s-app: fortune-teller-app
    spec:
      containers:
      - name: fortune-teller-app
        image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
        ports:
        - containerPort: 50051
          name: grpc
apiVersion: v1
kind: Service
metadata:
  name: fortune-teller-service
  namespace: haproxy-controller
spec:
  selector:
    k8s-app: fortune-teller-app
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
```
### Ingress.yaml
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-ingress-haproxy-controller
  namespace: haproxy-controller
spec:
  rules:
    - host: foo.bar
      http:
        paths:
           - backend:
              serviceName: fortune-teller-service
              servicePort: 50051
```
### Output of `haproxy POD
```
`10.244.0.1:41043 [18/Nov/2020:15:07:16.855] http haproxy-controller-fortune-teller-service-50051/SRV_XX0NX 0/0/1/-1/1 502 229 - - PH-- 1/1/0/0/0 0/0 "POST foo.bar/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0"
`
```
### config  in /etc/haproxy/haproxy.cfg

` Server SRV_XX0NX 10.244.0.183:50051 check alpn h2 weight 128 verify none`

can somebody suggest idea or fix please ?
Best regards.
